### ISSUE TITLE
New feature proposal 

### ISSUE THREAD

**Issue by asim-jaweesh** [TechArchSA/HackersNote#12]
The tool works perfectly now by creating the directory tree and associated files and folders, however if it can also initiate a git repo then fix it's settings it would be great, so the workflow will be something like:
1- take project name, target list and remote git repository name and url (4 cli parameters)
2- create directory tree with files and folders
3- initialize local git repo, add the files, them commit and push to master.

it can be broken down to more steps than that to ease development but i think i made the idea clear.

**Comment by KINGSABRI** [comment]
Done 
please install the gem 

```
gem install hackernote
```
