### ISSUE TITLE
[Bug] URL handling in long URLs

### ISSUE THREAD

**Issue by asim-jaweesh** [TechArchSA/HackersNote#14]
when you try to run the tools with a given complete url path like
`
hxxp://example.com/app1/route2/ 
`

the fails to create such a directory tree and throught the following error

`
ruby gitbook_builder.rb -p P1 -l hosts.txt  
[+] Gitbook Setup:  
[-] Creating P1 directory  
[-] Creating gitbook's main files.'
[-] Creating targets' files and directories.
gitbook_builder.rb:123:in 'mkdir'
gitbook_builder.rb:123:in 'block in build_targets_files'
gitbook_builder.rb:120:in 'each'
gitbook_builder.rb:120:in 'build_targets_files'
gitbook_builder.rb:54:in 'build'
gitbook_builder.rb:319:in '<main>'
gitbook_builder.rb:123:in 'mkdir'
gitbook_builder.rb:123:in 'block in build_targets_files'
gitbook_builder.rb:120:in 'each'
gitbook_builder.rb:120:in 'build_targets_files'
gitbook_builder.rb:54:in 'build'
gitbook_builder.rb:319:in '<main>'
No such file or directory @ dir_s_mkdir - example.com/app1/route2`

however the works fine if you edit the URL like

contents of hosts.txt
`
www.example.com-app1-route2
example.com
`

![2017-12-18_17h16_51](https://user-images.githubusercontent.com/4925223/34113566-c8674770-e418-11e7-90c3-d479eb9406d7.jpg)

**Comment by KINGSABRI** [comment]
fixed 
 
please install the gem 

```
gem install hackernote
```
